FROM node:24-alpine AS deps

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

FROM node:24-alpine AS builder

WORKDIR /app
ENV ASTRO_TELEMETRY_DISABLED=1
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ARG PUBLIC_API_BASE_URL=http://localhost:8080
ARG PUBLIC_API_FALLBACK_BASE_URL=
ARG PUBLIC_API_FETCH_TIMEOUT_MS=10000
ARG PUBLIC_BROWSER_API_BASE_URL=/backend
ARG PUBLIC_SITE_URL=https://www.gtcodestar.com
ARG PUBLIC_DEFAULT_LANG=en
ARG PUBLIC_TURNSTILE_SITE_KEY=
ENV PUBLIC_API_BASE_URL=$PUBLIC_API_BASE_URL
ENV PUBLIC_API_FALLBACK_BASE_URL=$PUBLIC_API_FALLBACK_BASE_URL
ENV PUBLIC_API_FETCH_TIMEOUT_MS=$PUBLIC_API_FETCH_TIMEOUT_MS
ENV PUBLIC_BROWSER_API_BASE_URL=$PUBLIC_BROWSER_API_BASE_URL
ENV PUBLIC_SITE_URL=$PUBLIC_SITE_URL
ENV PUBLIC_DEFAULT_LANG=$PUBLIC_DEFAULT_LANG
ENV PUBLIC_TURNSTILE_SITE_KEY=$PUBLIC_TURNSTILE_SITE_KEY
RUN npm run build

FROM nginx:1.27-alpine

COPY --from=builder /app/dist /usr/share/nginx/html
ARG NGINX_CONF=nginx.conf
COPY ${NGINX_CONF} /etc/nginx/conf.d/default.conf
EXPOSE 80
